[[main]]
none = "none"

[[main]]
name = "Personal Projects"
pre = ""
pageRef = "personal projects"
identifier = "KlGd9ORDzx"
weight = 9999

[[main]]
name = "Gamejams / Hackatons"
pageRef = "gamejam projects"
identifier = "1oa2nDh8De"
weight = 9999

[[main]]
name = "Published Games / Apps"
pageRef = "published games"
identifier = "zflo0ufXff"
weight = 9999

[[footer]]
none = "none"
